// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApz5IChbr4BSaXYy0q0kjp-iudn1VRYrA',
    appId: '1:992833737006:web:e7ab2ea69dbc9b35efaabf',
    messagingSenderId: '992833737006',
    projectId: 'crowdsense-db',
    authDomain: 'crowdsense-db.firebaseapp.com',
    storageBucket: 'crowdsense-db.firebasestorage.app',
    measurementId: 'G-FVVG32N0NE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkQ0mvlf05BppRHeVJhuexy1U2P4HIeRM',
    appId: '1:992833737006:android:33b938d19c45288defaabf',
    messagingSenderId: '992833737006',
    projectId: 'crowdsense-db',
    storageBucket: 'crowdsense-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvh6m2juiZDAyp42MlrzLdsPKjMWcmj5I',
    appId: '1:992833737006:ios:ca3ca4bb2a09f0c0efaabf',
    messagingSenderId: '992833737006',
    projectId: 'crowdsense-db',
    storageBucket: 'crowdsense-db.firebasestorage.app',
    iosBundleId: 'com.example.crowdSense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvh6m2juiZDAyp42MlrzLdsPKjMWcmj5I',
    appId: '1:992833737006:ios:ca3ca4bb2a09f0c0efaabf',
    messagingSenderId: '992833737006',
    projectId: 'crowdsense-db',
    storageBucket: 'crowdsense-db.firebasestorage.app',
    iosBundleId: 'com.example.crowdSense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApz5IChbr4BSaXYy0q0kjp-iudn1VRYrA',
    appId: '1:992833737006:web:852c55d9efe4633fefaabf',
    messagingSenderId: '992833737006',
    projectId: 'crowdsense-db',
    authDomain: 'crowdsense-db.firebaseapp.com',
    storageBucket: 'crowdsense-db.firebasestorage.app',
    measurementId: 'G-1VE4N5F9Q0',
  );
}
